### PR TITLE
chore: update deps

### PR DESCRIPTION
**Pull request by achingbrain**
Updates `Buffer` to the latest version as having multiple versions in
the dep tree causes quite a lot of bundle bloat when run in browsers!

### CODE REVIEW

**Comment by vweevers** [comment]
Semver-major because it drops support of IE11. @achingbrain Could you remove IE11 from `.airtap.yml`?

**Comment by achingbrain** [comment]
Done!

**Comment by vweevers** [comment]
Ran browser tests on a temporarily expanded matrix, all good! Safari 11 on Mac failed, but seeing as iOS Safari 11 did succeed, I think it was a random or at least unrelated failure. Will retry that.

image

**Comment by vweevers** [comment]
Was indeed unrelated. Safari threw `TypeError: Value is not a sequence` upon `console.log(..)`, which is caused by [the WebDriver extension that Sauce Labs has installed](https://github.com/apache/cordova-plugin-media-capture/issues/105#issuecomment-425052111) on MacOS 10.12, but luckily not on 10.13 so I switched to that. Tests passed.

**Comment by vweevers** [comment]
I've since removed the need for `buffer`: https://github.com/Level/abstract-leveldown/commit/8f792349bb940bac47152c7f02fae92c081afac7

**Comment by vweevers** [comment]
[7.0.0](https://github.com/Level/abstract-leveldown/releases/tag/v7.0.0)

**Pull request merged**
