### PR TITLE
null and undefined serializes to empty string

### PR DESCRIPTION
**Pull request by ralphtheninja**
Rebased https://github.com/Level/abstract-leveldown/pull/99 and added test for `undefined`

### CODE REVIEW

**Comment by ralphtheninja** [comment]
This means `level.js` doesn't have to add extra code to make the `put-get-del-test.js` to pass

**Comment by vweevers** [comment]
Why should null/undefined be serialized, rather than rejected?

**Comment by ralphtheninja** [comment]
> Why should null/undefined be serialized, rather than rejected?

Because these tests https://github.com/Level/abstract-leveldown/blob/master/abstract/put-get-del-test.js#L140-L141

**Comment by ralphtheninja** [comment]
`memdown` can also remove this code https://github.com/Level/memdown/blob/master/memdown.js#L148

**Comment by vweevers** [comment]
I meant, taking a step back, why do we have this test - and behavior - in the first place? In streams `null` signifies end, so that might be a reason to reject storage of `null` values outright. But I know the history of all this is complicated and I can't immediately recall previous decisions.

**Comment by ralphtheninja** [comment]
> I meant, taking a step back, why do we have this test - and behavior - in the first place?

_That_ is a very good question.

@juliangruber Hilfe.

I wouldn't mind dropping this and not allowing `null` nor `undefined`. But would mean a new major version. Right now I'm only concerned with fixing the damn tests ;)

**Pull request merged**
