### PR TITLE
Optional options

### PR DESCRIPTION
**Pull request by ralphtheninja**
Closes https://github.com/Level/abstract-leveldown/issues/63

### CODE REVIEW

**Comment by juliangruber** [comment]
+1

**Comment by ralphtheninja** [comment]
I'll rebase this.

**Comment by juliangruber** [comment]
this is a new major, right?

**Comment by ralphtheninja** [comment]
@juliangruber Yes this should be a new major since we have removed `.location` and replaced it with `.options`.

**Comment by juliangruber** [comment]
ok, then when do you think we should release this?

**Comment by ralphtheninja** [comment]
Today? :)

**Comment by ralphtheninja** [comment]
Let me merge master into this branch first. We can have this PR hanging for a while for others to comment.

**Comment by ralphtheninja** [comment]
@juliangruber I don't remember why this was closed. Not saying it should be re-opened, just wondering about the reasoning behind it. If we still should get rid of `.location` then make a new PR instead.

**Pull request closed without merging**
