### PR TITLE
Batch array: assert elements are objects

### LINKED ISSUE #138: Remove gaps from batch array?
If you do `db.batch([null])`, or any other falsy value, should `abstract-leveldown` filter it?

I noticed that memdown has its own `!array[i]` check in `_batch()`, so I wondered if that's a job for `abstract-leveldown`. We currently do have a `typeof array[i] !== 'object'` check, which I didn't git blame yet, but this doesn't catch `null`.

@juliangruber @ralphtheninja

### PR DESCRIPTION
**Pull request by vweevers**
Closes #138.

Breaking change, major.

### CODE REVIEW

**Comment by juliangruber** [comment]
For reference, pre-allocating the array is the fastest method [for big](https://jsperf.com/grow-array) and [small arrays](https://jsperf.com/grow-array-small/)

**Comment by ralphtheninja** [comment]
I just noticed that we're calling back on the same tick on multiple places. Creating new issue for this.

**Comment by vweevers** [comment]
@ralphtheninja also, my first instinct was to throw (because it's a programmer's error), instead of calling back with an error. But then I thought it should be the same as the lines below:

https://github.com/Level/abstract-leveldown/blob/a5069de9deef13fd1010e5d7b67107211cd48235/abstract-leveldown.js#L173-L174

What's our policy on that?

**Comment by vweevers** [comment]
Never mind, I realized we do that in order to wrap the error in levelup.

**Pull request merged**
